rules: []
rulesConfigs: []
hooks: []
pages: []
resourceServers:
  - name: Test App
    identifier: http://localhost:3000/api/
    allow_offline_access: true
    enforce_policies: false
    scopes:
      - value: user:read
        description: Read user(s)
      - value: user:delete
        description: Delete user
      - value: user:create
        description: Create user
      - value: user:update
        description: Update user
    signing_alg: RS256
    skip_consent_for_verifiable_first_party_clients: true
    token_dialect: access_token
    token_lifetime: 86400
    token_lifetime_for_web: 90
  - name: Test App v2
    identifier: http://localhost:3000/apiv2/
    allow_offline_access: true
    enforce_policies: false
    signing_alg: RS256
    skip_consent_for_verifiable_first_party_clients: true
    token_dialect: access_token
    token_lifetime: 90
    token_lifetime_for_web: 75
clients:
  - name: API Explorer Application
    app_type: non_interactive
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: Test Application
    allowed_clients: []
    allowed_logout_urls:
      - http://localhost:3000/
    app_type: regular_web
    callbacks:
      - http://localhost:3000/api/auth/callback
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 120
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: expiring
      leeway: 1
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      token_lifetime: 900
      idle_token_lifetime: 300
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
databases:
  - name: Username-Password-Authentication
    strategy: auth0
    enabled_clients:
      - API Explorer Application
      - Test Application
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      passwordPolicy: good
      strategy_version: 2
      brute_force_protection: true
    realms:
      - Username-Password-Authentication
connections:
  - name: google-oauth2
    strategy: google-oauth2
    enabled_clients:
      - API Explorer Application
      - Test Application
    is_domain_connection: false
    options:
      email: true
      scope:
        - email
        - profile
      profile: true
tenant:
  enabled_locales:
    - ja
    - en
  flags:
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  friendly_name: Auth0 | mryhryki
  picture_url: https://mryhryki.com/assets/image/share_image.jpeg
  sandbox_version: '16'
  support_email: auth0@mryhryki.com
  support_url: ''
  universal_login:
    colors:
      page_background: '#000000'
      primary: '#fa7009'
emailProvider: {}
emailTemplates: []
clientGrants:
  - client_id: Test Application
    audience: http://localhost:3000/api/
    scope: []
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: false
  - name: push-notification
    enabled: false
  - name: recovery-code
    enabled: false
  - name: sms
    enabled: false
  - name: webauthn-platform
    enabled: false
  - name: webauthn-roaming
    enabled: false
guardianFactorProviders: []
guardianFactorTemplates: []
guardianPolicies:
  policies: []
guardianPhoneFactorSelectedProvider:
  provider: auth0
guardianPhoneFactorMessageTypes:
  message_types: []
roles: []
branding:
  colors:
    page_background: '#000000'
    primary: '#fa7009'
  logo_url: https://mryhryki.com/assets/image/share_image.jpeg
  templates: []
prompts:
  customText: {}
  identifier_first: false
  universal_login_experience: new
migrations: {}
actions:
  - name: Test
    code: ./actions/Test/code.js
    dependencies: []
    deployed: true
    runtime: node16
    secrets: []
    status: built
    supported_triggers:
      - id: post-login
        version: v3
triggers:
  post-login:
    - action_name: Test
      display_name: Test
organizations: []
attackProtection:
  breachedPasswordDetection:
    enabled: false
    shields: []
    admin_notification_frequency: []
    method: standard
    stage:
      pre-user-registration:
        shields: []
  bruteForceProtection:
    enabled: true
    shields:
      - block
      - user_notification
    mode: count_per_identifier_and_ip
    allowlist: []
    max_attempts: 10
  suspiciousIpThrottling:
    enabled: true
    shields:
      - admin_notification
      - block
    allowlist: []
    stage:
      pre-login:
        max_attempts: 100
        rate: 864000
      pre-user-registration:
        max_attempts: 50
        rate: 1200
logStreams: []
themes: []
