import styles from "@/styles/Home.module.css";
import { getSession, withPageAuthRequired } from "@auth0/nextjs-auth0";
import { useUser } from "@auth0/nextjs-auth0/client";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Auth0 Next.js Example</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <div>Logged in as <strong>{user?.email ?? "(Unknown)"}</strong></div>
        <section>
          <h2>User info</h2>
          <pre>{JSON.stringify(user, null, 2)}</pre>
        </section>
        <section>
          <Link href="/api/auth/logout">Logout</Link>
        </section>
      </main>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired({
  getServerSideProps: async function getServerSideProps(ctx: GetServerSidePropsContext) {
    const session = await getSession(ctx.req, ctx.res);
    console.log("Session:", JSON.stringify(session, null, 2));
    return { props: {} };
  },
});
