import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0/client";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";

export default function Home() {
  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Auth0 Next.js Example</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <div>Logged in as <strong>{user?.email ?? "(Unknown)"}</strong></div>
        <section>
          <h2>User info</h2>
          <pre>{JSON.stringify(user, null, 2)}</pre>
        </section>
        <section>
          <a href="/api/auth/logout">Logout</a>
        </section>
      </main>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired();
